package com.tasteFlavor.persistence.dto;
// Generated 22/10/2017 05:48:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String email;
     private String name;
     private String neighborhood;
     private String password;
     private Set nextToVisits = new HashSet(0);
     private Set calificationPerUsers = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String email, String name, String neighborhood, String password) {
        this.email = email;
        this.name = name;
        this.neighborhood = neighborhood;
        this.password = password;
    }
    public Customer(String email, String name, String neighborhood, String password, Set nextToVisits, Set calificationPerUsers) {
       this.email = email;
       this.name = name;
       this.neighborhood = neighborhood;
       this.password = password;
       this.nextToVisits = nextToVisits;
       this.calificationPerUsers = calificationPerUsers;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNeighborhood() {
        return this.neighborhood;
    }
    
    public void setNeighborhood(String neighborhood) {
        this.neighborhood = neighborhood;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getNextToVisits() {
        return this.nextToVisits;
    }
    
    public void setNextToVisits(Set nextToVisits) {
        this.nextToVisits = nextToVisits;
    }
    public Set getCalificationPerUsers() {
        return this.calificationPerUsers;
    }
    
    public void setCalificationPerUsers(Set calificationPerUsers) {
        this.calificationPerUsers = calificationPerUsers;
    }




}


