package com.tasteFlavor.persistence.dto;
// Generated 22/10/2017 05:48:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FoodPlace generated by hbm2java
 */
public class FoodPlace  implements java.io.Serializable {


     private Integer id;
     private PlaceType placeType;
     private String name;
     private String address;
     private String phone;
     private String schedule;
     private String description;
     private String urlPage;
     private Set nextToVisits = new HashSet(0);
     private Set resources = new HashSet(0);
     private Set calificationPerUsers = new HashSet(0);
     private Set specialityPerFoodPlaces = new HashSet(0);

    public FoodPlace() {
    }

	
    public FoodPlace(PlaceType placeType, String name, String address, String phone, String schedule, String description, String urlPage) {
        this.placeType = placeType;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.schedule = schedule;
        this.description = description;
        this.urlPage = urlPage;
    }
    public FoodPlace(PlaceType placeType, String name, String address, String phone, String schedule, String description, String urlPage, Set nextToVisits, Set resources, Set calificationPerUsers, Set specialityPerFoodPlaces) {
       this.placeType = placeType;
       this.name = name;
       this.address = address;
       this.phone = phone;
       this.schedule = schedule;
       this.description = description;
       this.urlPage = urlPage;
       this.nextToVisits = nextToVisits;
       this.resources = resources;
       this.calificationPerUsers = calificationPerUsers;
       this.specialityPerFoodPlaces = specialityPerFoodPlaces;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PlaceType getPlaceType() {
        return this.placeType;
    }
    
    public void setPlaceType(PlaceType placeType) {
        this.placeType = placeType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUrlPage() {
        return this.urlPage;
    }
    
    public void setUrlPage(String urlPage) {
        this.urlPage = urlPage;
    }
    public Set getNextToVisits() {
        return this.nextToVisits;
    }
    
    public void setNextToVisits(Set nextToVisits) {
        this.nextToVisits = nextToVisits;
    }
    public Set getResources() {
        return this.resources;
    }
    
    public void setResources(Set resources) {
        this.resources = resources;
    }
    public Set getCalificationPerUsers() {
        return this.calificationPerUsers;
    }
    
    public void setCalificationPerUsers(Set calificationPerUsers) {
        this.calificationPerUsers = calificationPerUsers;
    }
    public Set getSpecialityPerFoodPlaces() {
        return this.specialityPerFoodPlaces;
    }
    
    public void setSpecialityPerFoodPlaces(Set specialityPerFoodPlaces) {
        this.specialityPerFoodPlaces = specialityPerFoodPlaces;
    }




}


