package com.tasteFlavor.persistence.dto;
// Generated 22/10/2017 05:48:02 PM by Hibernate Tools 4.3.1



/**
 * NextToVisit generated by hbm2java
 */
public class NextToVisit  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private FoodPlace foodPlace;
     private String state;

    public NextToVisit() {
    }

    public NextToVisit(Customer customer, FoodPlace foodPlace, String state) {
       this.customer = customer;
       this.foodPlace = foodPlace;
       this.state = state;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public FoodPlace getFoodPlace() {
        return this.foodPlace;
    }
    
    public void setFoodPlace(FoodPlace foodPlace) {
        this.foodPlace = foodPlace;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }




}


