package com.tasteFlavor.persistence.dto;
// Generated 22/10/2017 05:48:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PlaceType generated by hbm2java
 */
public class PlaceType  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set foodPlaces = new HashSet(0);

    public PlaceType() {
    }

	
    public PlaceType(String name) {
        this.name = name;
    }
    public PlaceType(String name, Set foodPlaces) {
       this.name = name;
       this.foodPlaces = foodPlaces;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getFoodPlaces() {
        return this.foodPlaces;
    }
    
    public void setFoodPlaces(Set foodPlaces) {
        this.foodPlaces = foodPlaces;
    }




}


