package com.tasteFlavor.persistence.dto;
// Generated 22/10/2017 05:48:02 PM by Hibernate Tools 4.3.1



/**
 * CalificationPerUser generated by hbm2java
 */
public class CalificationPerUser  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private FoodPlace foodPlace;
     private int calification;

    public CalificationPerUser() {
    }

    public CalificationPerUser(Customer customer, FoodPlace foodPlace, int calification) {
       this.customer = customer;
       this.foodPlace = foodPlace;
       this.calification = calification;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public FoodPlace getFoodPlace() {
        return this.foodPlace;
    }
    
    public void setFoodPlace(FoodPlace foodPlace) {
        this.foodPlace = foodPlace;
    }
    public int getCalification() {
        return this.calification;
    }
    
    public void setCalification(int calification) {
        this.calification = calification;
    }




}


