package com.tasteFlavor.persistence.dto;
// Generated 22/10/2017 05:48:02 PM by Hibernate Tools 4.3.1



/**
 * Resource generated by hbm2java
 */
public class Resource  implements java.io.Serializable {


     private Integer id;
     private FoodPlace foodPlace;
     private byte[] photo;

    public Resource() {
    }

    public Resource(FoodPlace foodPlace, byte[] photo) {
       this.foodPlace = foodPlace;
       this.photo = photo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FoodPlace getFoodPlace() {
        return this.foodPlace;
    }
    
    public void setFoodPlace(FoodPlace foodPlace) {
        this.foodPlace = foodPlace;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }




}


