package com.tasteFlavor.persistence.dto;
// Generated 22/10/2017 05:48:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Specialty generated by hbm2java
 */
public class Specialty  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set specialityPerFoodPlaces = new HashSet(0);

    public Specialty() {
    }

	
    public Specialty(String name) {
        this.name = name;
    }
    public Specialty(String name, Set specialityPerFoodPlaces) {
       this.name = name;
       this.specialityPerFoodPlaces = specialityPerFoodPlaces;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getSpecialityPerFoodPlaces() {
        return this.specialityPerFoodPlaces;
    }
    
    public void setSpecialityPerFoodPlaces(Set specialityPerFoodPlaces) {
        this.specialityPerFoodPlaces = specialityPerFoodPlaces;
    }




}


