package com.tasteFlavor.persistence.dto;
// Generated 22/10/2017 05:48:02 PM by Hibernate Tools 4.3.1



/**
 * SpecialityPerFoodPlace generated by hbm2java
 */
public class SpecialityPerFoodPlace  implements java.io.Serializable {


     private Integer id;
     private FoodPlace foodPlace;
     private Specialty specialty;
     private int amountOfPeople;

    public SpecialityPerFoodPlace() {
    }

    public SpecialityPerFoodPlace(FoodPlace foodPlace, Specialty specialty, int amountOfPeople) {
       this.foodPlace = foodPlace;
       this.specialty = specialty;
       this.amountOfPeople = amountOfPeople;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public FoodPlace getFoodPlace() {
        return this.foodPlace;
    }
    
    public void setFoodPlace(FoodPlace foodPlace) {
        this.foodPlace = foodPlace;
    }
    public Specialty getSpecialty() {
        return this.specialty;
    }
    
    public void setSpecialty(Specialty specialty) {
        this.specialty = specialty;
    }
    public int getAmountOfPeople() {
        return this.amountOfPeople;
    }
    
    public void setAmountOfPeople(int amountOfPeople) {
        this.amountOfPeople = amountOfPeople;
    }




}


